FROM public.ecr.aws/docker/library/python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:0.10.4 /uv /uvx /bin/

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY worker /app/worker
COPY app /app/app

ENV PATH="/app/.venv/bin:${PATH}"

CMD ["uv", "run", "celery", "-A", "worker.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
